@csrf
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Nama Lengkap</label><input name="name" value="{{ old('name', $admin->name ?? '') }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Email</label><input type="email" name="email" value="{{ old('email', $admin->email ?? '') }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Password @isset($admin)<span class="text-secondary small">(kosongkan jika tidak diubah)</span>@endisset</label><input type="password" name="password" class="form-control @error('password') is-invalid @enderror" @empty($admin) required @endempty>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Konfirmasi Password</label><input type="password" name="password_confirmation" class="form-control" @empty($admin) required @endempty></div>
    <div class="col-md-8"><label class="form-label">Wilayah</label><select name="wilayah_id" class="form-select @error('wilayah_id') is-invalid @enderror" required><option value="">Pilih wilayah</option>@foreach($wilayah as $item)<option value="{{ $item->id }}" @selected(old('wilayah_id', $admin->wilayah_id ?? '') == $item->id)>RT {{ $item->rt }} / RW {{ $item->rw }} — {{ $item->kelurahan }}, {{ $item->kecamatan }}</option>@endforeach</select>@error('wilayah_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select" required><option value="active" @selected(old('status', $admin->status ?? 'active') === 'active')>Aktif</option><option value="inactive" @selected(old('status', $admin->status ?? '') === 'inactive')>Tidak Aktif</option></select></div>
</div>
